# Generated by Django 5.1.1 on 2024-10-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pokemon_type', models.CharField(max_length=50)),
                ('level', models.IntegerField(max_length=250)),
                ('description', models.TextField()),
                ('sprite_url', models.URLField()),
            ],
        ),
    ]
