# Generated by Django 5.1.1 on 2024-10-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_pokemon_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('A', 'Apple'), ('B', 'Berry'), ('G', 'Grapes'), ('H', 'Hot Dog'), ('P', 'Pizza'), ('S', 'Sushi'), ('T', 'Tonkatsu')], default='A', max_length=1)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pokemon')),
            ],
        ),
    ]
