# Generated by Django 5.1.1 on 2024-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_item_alter_feeding_options_alter_feeding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.AddField(
            model_name='item',
            name='effect',
            field=models.CharField(default=69, max_length=200),
            preserve_default=False,
        ),
    ]
